### ISSUE TITLE
Update browser support on help page

### ISSUE THREAD

**Issue by llastowka-usgs** [usgs/earthquake-website#163]
http://earthquake.usgs.gov/earthquakes/map/doc_help.php#browser-support

Minor technicality, In the browser support section it is really Edge now and not Internet Explorer.  
Obviously not an urgent fix!

**Comment by lisa-usgs** [comment]
The doc_help.php webpage has been replaced by the http://earthquake.usgs.gov/data/comcat/latest-eqs.php#browser-support page, so I'll make the update to the new page and not the old page, which should be deleted when all the links to it have been updated.  I think the only links that haven't been updated are in Latest Earthquakes, until the Beta version replaces the current version.

If you want the old page updated, the web team will have to do that since it's part of the Latest Earthquakes web app.

**Comment by lisa-usgs** [comment]
Done and deployed.
