### ISSUE TITLE
Change title of significant events on home and earthquake pages

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-website#61]
"Significant Events" instead of "Significant Earthquakes", because not all significant events are earthquakes.

**Comment by llastowka-usgs** [comment]
Lisa pointed out that in MOST cases, earthquakes is a more appropriate description and would serve our audience better. I agree that "events" is more accurate, but we are the  National EARTHQUAKE information center so branding our information as such seems reasonable.

**Comment by lisa-usgs** [comment]
Here was my comment to Linda:

I understand not all events are earthquakes, but MOST of them are (99%+), and I think the word “Events” rather than “Earthquakes” would not be as meaningful to the general public, may confuse them, and may mean users not being able to find what they’re looking for.

This is a case where in the service of user-friendly, it’s better to be less than 100% accurate, unless someone can make a strong case why this is better for our users.

And I'm adding now:
Unless there are opposing responses within the next few days, I'll close this ticket.

**Comment by jmfee-usgs** [comment]
This was one of the options, Paul reported buildings were evacuated because the sonic boom appeared in the "Significant Earthquakes" list (even though it was magnitude 0).  This related issue may be sufficient by including event type in the link title, similar to the map/list and event pages:
https://github.com/usgs/earthquake-list-widget/issues/16

**Comment by paulearle** [comment]
I would prefer "Significant Events"  two recent cases the sonic boom and N. Korean nuclear test caused confusion in the press and public. This problem will likely be solved if the event type for non-earthquake events appears in the event listing so I'm willing to bend but prefer "Significant Events"

**Comment by lisa-usgs** [comment]
I talked to Paul, and he agrees it would be better to make the event name for non-earthquakes to say, for example, "M0.0 Sonic Boom - Southern New Jersey" in the earthquake list just like it says already in the title.  See http://earthquake.usgs.gov/earthquakes/eventpage/us20004vbk#general_region versus attached Homepage screenshot of significant EQ list.
![screen shot 2016-02-18 at 3 55 53 pm](https://cloud.githubusercontent.com/assets/4162494/13160992/36050a40-d658-11e5-848a-1b0391a7b052.png)
